"""Model-independent hyperparameter-selection planning utilities.

The public API in this package describes how forecast targets are grouped into
selection cells. Each cell stands for one system-wide hyperparameter vector
shared by all targets assigned to that cell.
"""

from .selection_scope import SelectionPlan, TargetCell, TargetKey, build_selection_plan
from .schedules import ScheduleError, SelectionEvent, SelectionSchedule
from .losses import (
    BenchmarkForecaster,
    CellDiagnostic,
    DuplicateErrorRecord,
    ForecastErrorRecord,
    LossConfig,
    LossConfigurationError,
    LossResult,
    MissingCellError,
    ScaleConfig,
    absolute_error,
    attach_benchmark_errors,
    compute_outer_report_metrics,
    evaluate_selection_loss,
    squared_error,
)
from .splits import (
    InfeasibleValidationDesign,
    ValidationScheme,
    ValidationSplit,
    VintagePolicy,
    assert_rolling_window_length,
    assert_sorted_deterministically,
    assert_split_is_leakage_safe,
    build_validation_splits,
    resolve_horizon_offsets,
    verify_validation_splits,
)
from .metadata import (
    DEFAULT_RELEVANT_PACKAGES,
    OUTPUT_SCHEMA_VERSION,
    build_run_metadata,
    classify_failure,
    fingerprint_input_file,
    fingerprint_input_files,
    package_versions,
    repository_state,
    sha256_file,
    stable_configuration_hash,
    stable_json_dumps,
    summarize_failures,
    utc_now,
)
from .io import (
    CSVSchema,
    JSONSchema,
    OutputValidationError,
    ResumeRejectedError,
    RUN_COMPLETE_FILENAME,
    RUN_MANIFEST_FILENAME,
    RUN_STATUS_FILENAME,
    RunDirectoryState,
    atomic_write_csv_rows,
    atomic_write_dataframe_csv,
    atomic_write_json,
    atomic_write_text,
    classify_run_directory,
    mark_run_cancelled,
    mark_run_complete,
    mark_run_failed,
    prepare_run_directory,
    resolve_run_directory_policy,
    validate_csv_schema,
    validate_json_schema,
    validate_outputs,
)

__all__ = [
    "TargetKey",
    "TargetCell",
    "SelectionPlan",
    "build_selection_plan",
    "ScheduleError",
    "SelectionEvent",
    "SelectionSchedule",
    "BenchmarkForecaster",
    "CellDiagnostic",
    "DuplicateErrorRecord",
    "ForecastErrorRecord",
    "LossConfig",
    "LossConfigurationError",
    "LossResult",
    "MissingCellError",
    "ScaleConfig",
    "absolute_error",
    "attach_benchmark_errors",
    "compute_outer_report_metrics",
    "evaluate_selection_loss",
    "squared_error",
    "InfeasibleValidationDesign",
    "ValidationScheme",
    "ValidationSplit",
    "VintagePolicy",
    "assert_rolling_window_length",
    "assert_sorted_deterministically",
    "assert_split_is_leakage_safe",
    "build_validation_splits",
    "resolve_horizon_offsets",
    "verify_validation_splits",
    "DEFAULT_RELEVANT_PACKAGES",
    "OUTPUT_SCHEMA_VERSION",
    "build_run_metadata",
    "classify_failure",
    "fingerprint_input_file",
    "fingerprint_input_files",
    "package_versions",
    "repository_state",
    "sha256_file",
    "stable_configuration_hash",
    "stable_json_dumps",
    "summarize_failures",
    "utc_now",
    "CSVSchema",
    "JSONSchema",
    "OutputValidationError",
    "ResumeRejectedError",
    "RUN_COMPLETE_FILENAME",
    "RUN_MANIFEST_FILENAME",
    "RUN_STATUS_FILENAME",
    "RunDirectoryState",
    "atomic_write_csv_rows",
    "atomic_write_dataframe_csv",
    "atomic_write_json",
    "atomic_write_text",
    "classify_run_directory",
    "mark_run_cancelled",
    "mark_run_complete",
    "mark_run_failed",
    "prepare_run_directory",
    "resolve_run_directory_policy",
    "validate_csv_schema",
    "validate_json_schema",
    "validate_outputs",
]